# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(612, 414)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.t2_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.t2_pass.setGeometry(QtCore.QRect(150, 180, 113, 22))
        self.t2_pass.setAutoFillBackground(False)
        self.t2_pass.setObjectName("t2_pass")
        self.l2_sign_up = QtWidgets.QLabel(self.centralwidget)
        self.l2_sign_up.setGeometry(QtCore.QRect(40, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l2_sign_up.setFont(font)
        self.l2_sign_up.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.l2_sign_up.setObjectName("l2_sign_up")
        self.t1_user = QtWidgets.QLineEdit(self.centralwidget)
        self.t1_user.setGeometry(QtCore.QRect(150, 130, 113, 22))
        self.t1_user.setObjectName("t1_user")
        self.l3_username = QtWidgets.QLabel(self.centralwidget)
        self.l3_username.setGeometry(QtCore.QRect(40, 160, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l3_username.setFont(font)
        self.l3_username.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.l3_username.setObjectName("l3_username")
        self.l4_password = QtWidgets.QLabel(self.centralwidget)
        self.l4_password.setGeometry(QtCore.QRect(130, 40, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.l4_password.setFont(font)
        self.l4_password.setAlignment(QtCore.Qt.AlignCenter)
        self.l4_password.setObjectName("l4_password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, -50, 471, 451))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../sugimori/249.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-50, 250, 211, 171))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../sugimori/250.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 161, 151))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../sugimori/645-incarnate.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.l3_username.raise_()
        self.label.raise_()
        self.t2_pass.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.l4_password.raise_()
        self.l2_sign_up.raise_()
        self.t1_user.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 612, 26))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login"))
        self.l2_sign_up.setText(_translate("LoginWindow", "User Name:"))
        self.l3_username.setText(_translate("LoginWindow", "Password:"))
        self.l4_password.setText(_translate("LoginWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
