# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(608, 391)
        SettingsWindow.setMinimumSize(QtCore.QSize(608, 391))
        SettingsWindow.setMaximumSize(QtCore.QSize(608, 391))
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b2_new_game = QtWidgets.QPushButton(self.centralwidget)
        self.b2_new_game.setGeometry(QtCore.QRect(240, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.b2_new_game.setFont(font)
        self.b2_new_game.setCheckable(False)
        self.b2_new_game.setObjectName("b2_new_game")
        self.b3_load_profile = QtWidgets.QPushButton(self.centralwidget)
        self.b3_load_profile.setGeometry(QtCore.QRect(240, 160, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.b3_load_profile.setFont(font)
        self.b3_load_profile.setCheckable(False)
        self.b3_load_profile.setObjectName("b3_load_profile")
        self.b4_records = QtWidgets.QPushButton(self.centralwidget)
        self.b4_records.setGeometry(QtCore.QRect(240, 220, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.b4_records.setFont(font)
        self.b4_records.setCheckable(False)
        self.b4_records.setObjectName("b4_records")
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 608, 22))
        self.menubar.setObjectName("menubar")
        SettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingsWindow)
        self.statusbar.setObjectName("statusbar")
        SettingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.b2_new_game.setText(_translate("SettingsWindow", "New Game"))
        self.b3_load_profile.setText(_translate("SettingsWindow", "Load Profile"))
        self.b4_records.setText(_translate("SettingsWindow", "Records"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsWindow = QtWidgets.QMainWindow()
    ui = Ui_SettingsWindow()
    ui.setupUi(SettingsWindow)
    SettingsWindow.show()
    sys.exit(app.exec_())
