# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignupGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignupWindow(object):
    def setupUi(self, SignupWindow):
        SignupWindow.setObjectName("SignupWindow")
        SignupWindow.resize(616, 414)
        self.centralwidget = QtWidgets.QWidget(SignupWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.t1_user = QtWidgets.QLineEdit(self.centralwidget)
        self.t1_user.setGeometry(QtCore.QRect(290, 110, 113, 22))
        self.t1_user.setObjectName("t1_user")
        self.l2_sign_up = QtWidgets.QLabel(self.centralwidget)
        self.l2_sign_up.setGeometry(QtCore.QRect(180, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l2_sign_up.setFont(font)
        self.l2_sign_up.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.l2_sign_up.setObjectName("l2_sign_up")
        self.l3_username = QtWidgets.QLabel(self.centralwidget)
        self.l3_username.setGeometry(QtCore.QRect(180, 140, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l3_username.setFont(font)
        self.l3_username.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.l3_username.setObjectName("l3_username")
        self.t2_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.t2_pass.setGeometry(QtCore.QRect(290, 160, 113, 22))
        self.t2_pass.setObjectName("t2_pass")
        self.l4_password = QtWidgets.QLabel(self.centralwidget)
        self.l4_password.setGeometry(QtCore.QRect(210, 10, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.l4_password.setFont(font)
        self.l4_password.setAlignment(QtCore.Qt.AlignCenter)
        self.l4_password.setObjectName("l4_password")
        self.l5_choose_pokemon = QtWidgets.QLabel(self.centralwidget)
        self.l5_choose_pokemon.setGeometry(QtCore.QRect(180, 200, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l5_choose_pokemon.setFont(font)
        self.l5_choose_pokemon.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.l5_choose_pokemon.setObjectName("l5_choose_pokemon")
        self.l6_pkmn1 = QtWidgets.QLabel(self.centralwidget)
        self.l6_pkmn1.setGeometry(QtCore.QRect(150, 260, 71, 61))
        self.l6_pkmn1.setStyleSheet("QLabel#label_5 {\n"
"    border: 2px solid black;\n"
"}\n"
"QLabel#label_5:pressed {\n"
"    border: 2px solid red;\n"
"}")
        self.l6_pkmn1.setText("")
        self.l6_pkmn1.setPixmap(QtGui.QPixmap("sugimori/1.png"))
        self.l6_pkmn1.setScaledContents(True)
        self.l6_pkmn1.setObjectName("l6_pkmn1")
        self.l7_pkmn4 = QtWidgets.QLabel(self.centralwidget)
        self.l7_pkmn4.setGeometry(QtCore.QRect(260, 260, 71, 61))
        self.l7_pkmn4.setStyleSheet("QLabel#label_6 {\n"
"    border: 2px solid black;\n"
"}\n"
"QLabel#label_6:pressed {\n"
"    border: 2px solid red;\n"
"}")
        self.l7_pkmn4.setText("")
        self.l7_pkmn4.setPixmap(QtGui.QPixmap("sugimori/4.png"))
        self.l7_pkmn4.setScaledContents(True)
        self.l7_pkmn4.setObjectName("l7_pkmn4")
        self.l8_pkmn7 = QtWidgets.QLabel(self.centralwidget)
        self.l8_pkmn7.setGeometry(QtCore.QRect(360, 260, 71, 61))
        self.l8_pkmn7.setStyleSheet("QLabel#label_7 {\n"
"    border: 2px solid black;\n"
"}\n"
"QLabel#label_7:pressed {\n"
"    border: 2px solid red;\n"
"}")
        self.l8_pkmn7.setText("")
        self.l8_pkmn7.setPixmap(QtGui.QPixmap("sugimori/7.png"))
        self.l8_pkmn7.setScaledContents(True)
        self.l8_pkmn7.setObjectName("l8_pkmn7")
        self.b5_sign_up = QtWidgets.QPushButton(self.centralwidget)
        self.b5_sign_up.setGeometry(QtCore.QRect(270, 340, 75, 24))
        self.b5_sign_up.setObjectName("b5_sign_up")
        SignupWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignupWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 616, 22))
        self.menubar.setObjectName("menubar")
        SignupWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SignupWindow)
        self.statusbar.setObjectName("statusbar")
        SignupWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SignupWindow)
        QtCore.QMetaObject.connectSlotsByName(SignupWindow)

    def retranslateUi(self, SignupWindow):
        _translate = QtCore.QCoreApplication.translate
        SignupWindow.setWindowTitle(_translate("SignupWindow", "Sign Up"))
        self.l2_sign_up.setText(_translate("SignupWindow", "User Name:"))
        self.l3_username.setText(_translate("SignupWindow", "Password:"))
        self.l4_password.setText(_translate("SignupWindow", "Sign Up"))
        self.l5_choose_pokemon.setText(_translate("SignupWindow", "Choose your starter pokemon!"))
        self.b5_sign_up.setText(_translate("SignupWindow", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignupWindow = QtWidgets.QMainWindow()
    ui = Ui_SignupWindow()
    ui.setupUi(SignupWindow)
    SignupWindow.show()
    sys.exit(app.exec_())
