# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WelcomeGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWindow(object):
    def setupUi(self, WelcomeWindow):
        WelcomeWindow.setObjectName("WelcomeWindow")
        WelcomeWindow.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WelcomeWindow.sizePolicy().hasHeightForWidth())
        WelcomeWindow.setSizePolicy(sizePolicy)
        WelcomeWindow.setMinimumSize(QtCore.QSize(608, 391))
        WelcomeWindow.setMaximumSize(QtCore.QSize(608, 391))
        self.centralwidget = QtWidgets.QWidget(WelcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l1_Welcome = QtWidgets.QLabel(self.centralwidget)
        self.l1_Welcome.setGeometry(QtCore.QRect(100, 130, 407, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.l1_Welcome.setFont(font)
        self.l1_Welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.l1_Welcome.setObjectName("l1_Welcome")
        self.b1_start_game = QtWidgets.QPushButton(self.centralwidget)
        self.b1_start_game.setGeometry(QtCore.QRect(260, 210, 75, 23))
        self.b1_start_game.setObjectName("b1_start_game")
        WelcomeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WelcomeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 608, 22))
        self.menubar.setObjectName("menubar")
        WelcomeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WelcomeWindow)
        self.statusbar.setObjectName("statusbar")
        WelcomeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(WelcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

    def retranslateUi(self, WelcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWindow.setWindowTitle(_translate("WelcomeWindow", "Welcome"))
        self.l1_Welcome.setText(_translate("WelcomeWindow", "Welcome To the Pokemon League"))
        self.b1_start_game.setText(_translate("WelcomeWindow", "Start Game"))
